### ISSUE TITLE
Update the DX documents with the latest Syncromatics.Engineering.DX.Common template

### ISSUE THREAD

**Issue by thzinc** [syncromatics/csvialize#3]
# Overview

The Syncromatics.Engineering.DX.Common template was recently updated to include a new email address.

# Implementation notes

* [Ensure the Syncromatics.Engineering.DX.Common template is installed](https://github.com/syncromatics/Syncromatics.Engineering.DX.Common#quickstart)
* In the root of the project folder, run `dotnet new syncdx-common --force --projectName TheActualProjectName --githubRepo TheActualGithubRepoName --nugetPackage TheActualNugetPackageName`
* Edit the `README.md` file to include the bits that are relevant to this project.

**Comment by lhermanson** [comment]
I'll take this one

**Comment by thzinc** [comment]
Thanks @lhermanson!
